## Breedables
## By: ShaneBee

settings:

  pregnancy:
    # Seconds the mother will be pregnant for
    seconds-til-birth:
      chicken: 300
      sheep: 300
      cow: 300
      pig: 300
      wolf: 100
      cat: 200
      rabbit: 400
    # Seconds the mother will be unable to breed for after giving birth
    seconds-til-breedable:
      chicken: 300
      sheep: 300
      cow: 300
      pig: 300
      wolf: 100
      cat: 200
      rabbit: 400
    # Min/Max amount of offspring when the mother gives birth
    offspring:
      chicken: 3;8
      sheep: 3;4
      cow: 3;4
      pig: 3;5
      wolf: 1;3
      cat: 2;6
      rabbit: 4;10


  baby:
    # Seconds til the baby grows up to be an adult
    seconds-til-adult:
      chicken: 600
      sheep: 600
      cow: 600
      pig: 600
      wolf: 600
      cat: 600
      rabbit: 1200