

settings:

  pregnancy:
    # Seconds the mother will be pregnant for
    seconds-til-birth:
      chicken: 300
      sheep: 300
      cow: 300
      pig: 300
      wolf: 100
      cat: 200
      rabbit: 400
    # Seconds the mother will be unable to breed for after giving birth
    seconds-til-breedable:
      chicken: 300
      sheep: 300
      cow: 300
      pig: 300
      wolf: 100
      cat: 200
      rabbit: 400
    # Min/Max amount of offspring when the mother gives birth
    offspring:
      min:
        chicken: 3
        sheep: 3
        cow: 3
        pig: 3
        wolf: 1
        cat: 2
        rabbit: 4
      max:
        chicken: 8
        sheep: 4
        cow: 4
        pig: 5
        wolf: 3
        cat: 6
        rabbit: 10

  baby:
    # Seconds til the baby grows up to be an adult
    seconds-til-adult:
      chicken: 8
      sheep: 4
      cow: 4
      pig: 5
      wolf: 3
      cat: 6
      rabbit: 10