## Breedables
## By: ShaneBee

enabled-worlds:
  - world

entity-data:
  cow:
    # Seconds the mother will be pregnant for
    seconds-til-birth: 6000
    # Seconds until the entity can breed again
    # (for mothers, this will start after giving birth)
    seconds-til-breedable: 300
    # Min;Max amount of offspring when the mother gives birth
    offspring: 3;4
    # Seconds til the baby grows up to be an adult
    seconds-til-adult: 3600
  chicken:
    seconds-til-birth: 6000
    seconds-til-breedable: 300
    offspring: 4;8
    seconds-til-adult: 3600
  sheep:
    seconds-til-birth: 6000
    seconds-til-breedable: 300
    offspring: 3;4
    seconds-til-adult: 3600
  pig:
    seconds-til-birth: 6000
    seconds-til-breedable: 300
    offspring: 3;4
    seconds-til-adult: 3600
  rabbit:
    seconds-til-birth: 6000
    seconds-til-breedable: 300
    offspring: 3;4
    seconds-til-adult: 3600
  wolf:
    seconds-til-birth: 6000
    seconds-til-breedable: 300
    offspring: 3;4
    seconds-til-adult: 3600
  cat:
    seconds-til-birth: 6000
    seconds-til-breedable: 300
    offspring: 3;4
    seconds-til-adult: 3600