## Breedables
## By: ShaneBee

settings:
  enabled-worlds:
    - world

  pregnancy:
    # Seconds the mother will be pregnant for
    seconds-til-birth:
      chicken: 6000
      sheep: 6000
      cow: 6000
      pig: 6000
      wolf: 6000
      cat: 6000
      rabbit: 9000
    # Seconds the mother will be unable to breed for after giving birth
    seconds-til-breedable:
      chicken: 300
      sheep: 300
      cow: 300
      pig: 300
      wolf: 100
      cat: 200
      rabbit: 400
    # Min;Max amount of offspring when the mother gives birth
    offspring:
      chicken: 3;8
      sheep: 3;4
      cow: 3;4
      pig: 3;5
      wolf: 1;3
      cat: 2;6
      rabbit: 4;10

  baby:
    # Seconds til the baby grows up to be an adult
    seconds-til-adult:
      chicken: 3600
      sheep: 3600
      cow: 3600
      pig: 3600
      wolf: 3600
      cat: 3600
      rabbit: 7200